shadow = false;
shadow-radius = 20;   # Set to 0 to remove blur, or a small number for minimal blur
shadow-opacity = 0.5;  # Adjust as needed
shadow-offset-x = 0;  # Change this to control shadow position
shadow-offset-y = 0;  # Change this to control shadow position
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c"
];
backend = "glx"
vsync = true;

fading = true;
fade-delta = 3;
fade-in-step = 0.04;
fade-out-step = 0.03;

shadow-exclude = [
  "class_g = 'sowm'"
];

blur-background-exclude = [
  "class_g = 'sowm'"
];

opacity-rule = [
  "100:class_g = 'sowm'"
];
unredir-if-possible = false;
frame-opacity = 1.0;


